// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexCore.Models.EFModels
{
    public partial class ProductImgs
    {
        public int ProductImgId { get; set; }
        public string fk_ProductId { get; set; }
        public int? fk_ColorId { get; set; }
        public string ImgPath { get; set; }

        public virtual ColorCategories fk_Color { get; set; }
        public virtual Products fk_Product { get; set; }
    }
}